export interface Company {
  id: number;
  name: string;
  description: string;
  category: string;
  initials: string;
}

export const companies: Company[] = [
  {
    id: 1,
    name: "Google",
    description: "Search, cloud, AI and consumer technology.",
    category: "Technology",
    initials: "G",
  },
  {
    id: 2,
    name: "Microsoft",
    description: "Software, cloud computing and enterprise technology.",
    category: "Technology",
    initials: "M",
  },
  {
    id: 3,
    name: "Amazon",
    description: "E-commerce, cloud computing and technology.",
    category: "Technology",
    initials: "A",
  },
  {
    id: 4,
    name: "Apple",
    description: "Consumer electronics, software and services.",
    category: "Technology",
    initials: "A",
  },
  {
    id: 5,
    name: "Meta",
    description: "Social platforms, advertising and technology.",
    category: "Technology",
    initials: "M",
  },
  {
    id: 6,
    name: "Netflix",
    description: "Streaming entertainment and original content.",
    category: "Entertainment",
    initials: "N",
  },
  {
    id: 7,
    name: "Adobe",
    description: "Creative software and digital experiences.",
    category: "Software",
    initials: "A",
  },
  {
    id: 8,
    name: "Spotify",
    description: "Music and audio streaming platform.",
    category: "Entertainment",
    initials: "S",
  },
  {
    id: 9,
    name: "Uber",
    description: "Mobility, delivery and transportation technology.",
    category: "Transportation",
    initials: "U",
  },
  {
    id: 10,
    name: "Airbnb",
    description: "Online marketplace for stays and experiences.",
    category: "Travel",
    initials: "A",
  },
  {
    id: 11,
    name: "Tesla",
    description: "Electric vehicles and clean energy.",
    category: "Automotive",
    initials: "T",
  },
  {
    id: 12,
    name: "Nvidia",
    description: "Semiconductors, GPUs and accelerated computing.",
    category: "Technology",
    initials: "N",
  },
  {
    id: 13,
    name: "OpenAI",
    description: "Artificial intelligence research and products.",
    category: "AI",
    initials: "O",
  },
  {
    id: 14,
    name: "Stripe",
    description: "Financial infrastructure and payment technology.",
    category: "Fintech",
    initials: "S",
  },
  {
    id: 15,
    name: "Notion",
    description: "Workspace and productivity software.",
    category: "Productivity",
    initials: "N",
  },
  {
    id: 16,
    name: "Atlassian",
    description: "Collaboration and developer productivity tools.",
    category: "Software",
    initials: "A",
  },
  {
    id: 17,
    name: "Salesforce",
    description: "Customer relationship management software.",
    category: "Enterprise",
    initials: "S",
  },
  {
    id: 18,
    name: "Shopify",
    description: "Commerce platform for businesses.",
    category: "E-commerce",
    initials: "S",
  },
  {
    id: 19,
    name: "LinkedIn",
    description: "Professional networking and career platform.",
    category: "Social",
    initials: "L",
  },
  {
    id: 20,
    name: "Slack",
    description: "Business communication and collaboration.",
    category: "Productivity",
    initials: "S",
  },
  {
    id: 21,
    name: "GitHub",
    description: "Developer platform for collaboration and code.",
    category: "Developer",
    initials: "G",
  },
  {
    id: 22,
    name: "Dropbox",
    description: "Cloud storage and collaboration platform.",
    category: "Productivity",
    initials: "D",
  },
  {
    id: 23,
    name: "Canva",
    description: "Online visual design and publishing platform.",
    category: "Design",
    initials: "C",
  },
  {
    id: 24,
    name: "Figma",
    description: "Collaborative interface design software.",
    category: "Design",
    initials: "F",
  },
  {
    id: 25,
    name: "Zoom",
    description: "Video communications and collaboration platform.",
    category: "Communication",
    initials: "Z",
  },
];
